CREATE EXTENSION pgcrypto;

CREATE EXTENSION IF NOT EXISTS "uuid-ossp";

CREATE TABLE Users (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    EMAIL VARCHAR(255) UNIQUE NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    ROLE VARCHAR(20) DEFAULT 'USER',
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IngredientRequest (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    STATUS VARCHAR(50),
    RESOURCE VARCHAR(500),
    USER_ID UUID
);


CREATE TABLE ParsedIngredientList (
    ID UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    REQUEST_ID UUID NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    DATA JSONB,


    CONSTRAINT fk_ingredient_request
      FOREIGN KEY(REQUEST_ID)
      REFERENCES IngredientRequest(ID)
      ON DELETE CASCADE
};